name: encrypto
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.14.0-178.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8
  file_picker: ^3.0.3
  permission_handler: 8.0.0
  # aes_crypt: ^0.1.1
  path_provider: ^2.0.5
  #ext_storage: ^1.0.3
  aes_crypt_null_safe: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/iconmonstr-shield-27-240.png
